name: Lint

on:
  schedule:
    - cron:  '0 12 */7 * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        uses: max/awesome-lint@v2.0.0
