name: Lint

on:
  schedule:
    - cron:  '0 12 */7 * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint
        run: npx awesome-lint
